apiVersion: v2
name: outline
description: Outline Helm chart
type: application
version: 0.1.0
appVersion: "0.75.2"
dependencies:
  - name: postgresql
    condition: postgresql.enabled
    version: "15.2.5"
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    condition: redis.enabled
    version: "19.1.0"
    repository: https://charts.bitnami.com/bitnami
  - name: minio
    condition: minio.enabled
    version: "14.1.7"
    repository: https://charts.bitnami.com/bitnami
