apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.databaseUrlSecretName" . }}
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ include "outline.databaseUrl" . | b64enc }}

---

{{- if (include "outline.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.secretName" . }}
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secretKeys.secretKey }}: {{ include "outline.secretKey" . | b64enc }}
  {{ .Values.secretKeys.utilsSecretKey }}: {{ include "outline.utilsSecretKey" . | b64enc }}
{{- end }}

---

{{- if (include "outline.google.createSecret" .) }}
{{- $googleClientId := .Values.auth.google.clientId | required ".Values.auth.google.clientId is required" -}}
{{- $googleClientSecret := .Values.auth.google.clientSecret | required ".Values.auth.google.clientSecret is required" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.google.secretName" . }}
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.google.secretKeys.clientId }}: {{ $googleClientId | b64enc }}
  {{ .Values.auth.google.secretKeys.clientSecret }}: {{ $googleClientSecret | b64enc }}
{{- end }}
